/**
 * Evolution mode allows to specify how strict is evitaDB when unknown information is presented to her for the first
 * time. When no evolution mode is set, each violation of the entity schema is
 * reported by an exception. This behaviour can be changed by this evolution mode, however.
 */
export enum EvolutionMode {
    /**
     * When first entity is inserted in the collection - primary key generation will automatically adapt whether
     * this first entity has the primary key already present or not. If it is present all other entities are expected
     * to have also primary key provided from external systems, if not primary keys will be always automatically
     * generated by Evita and may never be provided from outside.
     */
    AdaptPrimaryKeyGeneration = 'adaptPrimaryKeyGeneration',
    /**
     * When new attribute is encountered, it is silently added to a collection schema as non-filterable, non-sortable,
     * non-unique attribute of the type that was used for the first value. Localizability of the attribute is determined
     * by the fact whether the first value encountered was associated with any locale.
     */
    AddingAttributes = 'addingAttributes',
    /**
     * When new associated data is encountered, it is silently added to a collection schema. Localizability of
     * the associated data is determined by the fact whether the first value encountered was associated with any
     * locale.
     */
    AddingAssociatedData = 'addingAssociatedData',
    /**
     * When new reference type is encountered, it is silently added. It's linked to other evitaDB entity when
     * the referenced entity type or group respectively matches by
     * type any existing entity collection. Reference is not indexed, nor
     * hierarchy indexed by default and this must be changed by updating the schema.
     */
    AddingReferences = 'addingReferences',
    /**
     * When entity has no prices and new price is encountered, it is silently added. That means that entity type
     * starts supporting prices when first price has been added.
     */
    AddingPrices = 'addingPrices',
    /**
     * When new locale is encountered, it is silently added.
     */
    AddingLocales = 'addingLocales',
    /**
     * When new currency is encountered in prices, it is silently added.
     */
    AddingCurrencies = 'addingCurrencies',
    /**
     * When hierarchy placement for the entity is encountered, it is silently added.
     */
    AddingHierarchy = 'addingHierarchy'
}
