/**
 * List of support scalars supported by evitaDB.
 */
export enum Scalar {
    String = 'String',
    StringArray = 'StringArray',
    Byte = 'Byte',
    ByteArray = 'ByteArray',
    Short = 'Short',
    ShortArray = 'ShortArray',
    Integer = 'Integer',
    IntegerArray = 'IntegerArray',
    Long = 'Long',
    LongArray = 'LongArray',
    Boolean = 'Boolean',
    BooleanArray = 'BooleanArray',
    Character = 'Character',
    CharacterArray = 'CharacterArray',
    BigDecimal = 'BigDecimal',
    BigDecimalArray = 'BigDecimalArray',
    OffsetDateTime = 'OffsetDateTime',
    OffsetDateTimeArray = 'OffsetDateTimeArray',
    LocalDateTime = 'LocalDateTime',
    LocalDateTimeArray = 'LocalDateTimeArray',
    LocalDate = 'LocalDate',
    LocalDateArray = 'LocalDateArray',
    LocalTime = 'LocalTime',
    LocalTimeArray = 'LocalTimeArray',
    DateTimeRange = 'DateTimeRange',
    DateTimeRangeArray = 'DateTimeRangeArray',
    BigDecimalNumberRange = 'BigDecimalNumberRange',
    BigDecimalNumberRangeArray = 'BigDecimalNumberRangeArray',
    ByteNumberRange = 'ByteNumberRange',
    ByteNumberRangeArray = 'ByteNumberRangeArray',
    ShortNumberRange = 'ShortNumberRange',
    ShortNumberRangeArray = 'ShortNumberRangeArray',
    IntegerNumberRange = 'IntegerNumberRange',
    IntegerNumberRangeArray = 'IntegerNumberRangeArray',
    LongNumberRange = 'LongNumberRange',
    LongNumberRangeArray = 'LongNumberRangeArray',
    Locale = 'Locale',
    LocaleArray = 'LocaleArray',
    Currency = 'Currency',
    CurrencyArray = 'CurrencyArray',
    UUID = 'UUID',
    UUIDArray = 'UUIDArray',
    Predecessor = 'Predecessor',
    ComplexDataObject = 'ComplexDataObject'
}
